[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gigq"
description = "A lightweight job queue system with SQLite backend"
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}